version: '2'

networks:
  landscape-network:
    driver: bridge

services:

  landscape-postgres:
    #image
    container_name: landscape-postgres
    build: conf/postgres
    networks:
      - landscape-network
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
      POSTGRES_PASSWORD: 'MF'

  landscape-back:
    container_name: landscape-back
    build: .
    networks:
      - landscape-network
    ports:
      - 9000:9000
    command: ["./wait-for-postgres.sh", "postgre:5432", "./buletracer"]
